# On vote, plugin will forward the votifier vote to the following servers
# Put in the votifier information for each server below
# ServiceSite is not needed. Leave blank if you don't need it.

Servers:
  # Server, don't have 2 names the same
  # Name can be really anything, recommend server name
  Server1:
    # Votifier IP
    IP: ''
    # Votifier port
    Port: 8129
    # Votifier key of this server
    Key: 'PUBLICKEY'
    # Add custom service site, leave blank to use the service site from the vote
    ServiceSite: ''