name: VoteForwarder
version: 1.0
main: com.Ben12345rocks.VoteForwarder.Main
description: Forward votes to other servers!
author: Ben12345rocks
commands:
  voteforwarder:
    description: VoteForwarder Command
    aliases: vf